### PR TITLE
HDDS-1634. Introduce a new ozone specific runner image

### PR DESCRIPTION
**Pull request by elek**

### CODE REVIEW

**Comment by eyanghwx** [comment]
Hard code krb5.conf is not a good idea.  It might be creating conflicts with real host level configuration.  I recommend to mount krb5.conf from host, or from development test resource during testing phase.

**Comment by elek** [comment]
>  It might be creating conflicts with real host level configuration

Thanks the feedback @eyanghwx. Can you please help me to understand this problem? How can it be conflicted with a host file as it is part of the container? 

This is not a hardcoded version, but a default version.

**Comment by eyanghwx** [comment]
"hadoop" is configured as user uid 1000 in the container.  Host level
configuration may have Fred as uid 1000.  When /data or /var/log are
mounted to host disk, all the data generated by hadoop user are owned by
Fred.  This is what I call out as conflict of interest between container
and host.

regards,
Eric

**Comment by elek** [comment]
Thanks to explain it @eyanghwx  This is how containers are working, I can't see any problem.

But how is it related to the krb5.conf *inside* the container? 

(And please note that this is a [development specific image](https://cwiki.apache.org/confluence/display/HADOOP/Ozone+Docker+images), not for production)

**Comment by anuengineer** [comment]
+1, I think these are examples and NOT production images. I will commit this by End of today if I don't hear from any one. Thanks

**Comment by eyanghwx** [comment]
-1, must use host level uid instead of hard coded hadoop user for development.

**Comment by anuengineer** [comment]
Fanstastic Eric. Let us abandon this.

**Comment by anuengineer** [comment]
I am also -1 on this idea itself. Let us not even pursue this, since the has nothing do with Hadoop more focused on K8s. And I hate it when people just waste my time.

**Comment by arp7** [comment]
@eyanghwx what would be the straightforward way to incorporate your suggestion i.e. have a host-level uid?

**Comment by anuengineer** [comment]
It is standard practice in the Container / K8s world. So while I respect the -1; and closed this discussion and patch, I firmly believe Eric is wrong.

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by eyanghwx** [comment]
I withdrew my -1.  I am overly concerned with hard coded uid, which will be addressed in HDDS-1609.

@anuengineer security-context shows to pass runAsUser, runAsGroup, which is inline with the proposal in HDDS-1609 solution 1.  I wouldn't depend on fsGroup feature from Kubernetes to make data output permission proper because there are many [out standing issues](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+fsGroup) associated with fsGroup mapping.

**Comment by anuengineer** [comment]
Thanks, I will merge this now then.

**Comment by arp7** [comment]
Thank you @eyanghwx for withdrawing the veto. Let's discuss UID issue on HDDS-1609 filed by you.
I intend to commit this shortly based on @anuengineer 's +1 unless Anu objects.

**Comment by arp7** [comment]
Just saw Anu already merged this, thanks!

**Pull request merged**
