### PR TITLE
HDDS-11767. Use closer.lua in Ozone images

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Most Ozone images download binaries from dlcdn.  They cannot be rebuilt after old releases are removed from mirrors.  Replace the URL with one that is supposed to work for both new and old binaries.

Also, extract version number to argument to reduce duplication.

https://issues.apache.org/jira/browse/HDDS-11767

## How was this patch tested?

Version that is currently mirrored:

```
$ curl -L --head "https://www.apache.org/dyn/closer.lua?action=download&filename=ozone/1.4.0/ozone-1.4.0.tar.gz"
HTTP/2 302 
...
location: https://dlcdn.apache.org/ozone/1.4.0/ozone-1.4.0.tar.gz
...

HTTP/2 200 
...
content-length: 482009796
...
```

Archived version:

```
curl -L --head "https://www.apache.org/dyn/closer.lua?action=download&filename=ozone/1.3.0/ozone-1.3.0.tar.gz"
HTTP/2 302 
...
location: https://archive.apache.org/dist/ozone/1.3.0/ozone-1.3.0.tar.gz
...

HTTP/1.1 200 OK
...
Content-Length: 427860880
...
```

CI build:
https://github.com/adoroszlai/ozone-docker/actions/runs/11947909528/job/33304613875#step:7:442

### CODE REVIEW

**Comment by adoroszlai** [comment]
Also tested by applying d1bb3b64b704d7fb2e7f251bc263b4479ccecb6e with runner version updated to `20241121-1-jdk11` (the one from https://github.com/apache/ozone-docker-runner/commit/0b0afa1c93bd10498854d5e1132e61f788a64832), and the current change on top of `ozone-1.3.0-rocky` and earlier branches:

- 1.3.0: `ghcr.io/adoroszlai/ozone:f84fcfea84161f2ff0dc64ceca15e5c71349c795`
- 1.2.1: `ghcr.io/adoroszlai/ozone:98a3ce8536469c9f9d11e239b4ed8ae53283261e`
- 1.1.0: `ghcr.io/adoroszlai/ozone:02f00d86a6307373a74751cc96fc3826b031f8d0`
- 1.0.0: `ghcr.io/adoroszlai/ozone:60af14c585424793f08aa233fde785d753b6d0fa`

**Review by smengcl — APPROVED** [review]
lgtm. Thanks @adoroszlai .

btw are `dlcdn.apache.org` and `archive.apache.org` the only two possible domains `closer.lua` can redirect to?

**Comment by adoroszlai** [comment]
Thanks @smengcl for the review.

> btw are `dlcdn.apache.org` and `archive.apache.org` the only two possible domains `closer.lua` can redirect to?

There used to be multiple mirrors, but they were "aggregated" into `dlcdn`.

**Comment by smengcl** [comment]
Thanks @adoroszlai for the explanation.

I bumped into the prod source code for `closer.lua` here:

https://github.com/apache/infrastructure-p6/blob/production/modules/closer_cgi/files/closer.lua#L57

Looks like `downloads.apache.org` is also being used in some case, but I am not so sure.

**Pull request merged**
