### PR TITLE
HDDS-1526. Publish latest ozone release on dockerhub.

### PR DESCRIPTION
**Pull request by elek**
As 0.4.0-alpha is released we can publish the latest stable version on dockerhub.

Required steps:

 * Update ozone-latest branch in apache/hadoop-docker-ozone repository.
 * Create a new branch ozone-0.4.0 from the ozone-latest

Dockerhub is configured to create new tags from any branch which starts with ozone-:

branchname: ozone-XXXX --> docker image: apache/ozone:XXXX

Note: this releasing is in sync with ASF policies (See LEGAL-270)

bq. The main Docker Hub at hub.docker.com is a public-facing downstream
distribution channel – similar to Maven Central, PyPI, Debian package
management, etc.

bq. It is appropriate to distribute official releases through downstream channels, but inappropriate to distribute unreleased materials through them. (That's
why having `latest` on hub.docker.com point to git `master` is problematic.)
See Apache's formal Release Policy and Release Distribution Policy documents

This is a downstream distribution of the already voted and release ozone package. Please note that the Dockerfile points to the official download page. 

The ozone version command can show that we have exactly the same, voted and released bits inside: 

```
docker run apache/ozone:latest ozone version
                  //////////////                 
               ////////////////////              
            ////////     ////////////////        
           //////      ////////////////          
          /////      ////////////////  /         
         /////            ////////   ///         
         ////           ////////    /////        
        /////         ////////////////           
        /////       ////////////////   //        
         ////     ///////////////   /////        
         /////  ///////////////     ////         
          /////       //////      /////          
           //////   //////       /////           
             ///////////     ////////            
               //////  ////////////              
               ///   //////////                  
              /    0.4.0-alpha(Badlands)

Source code repository https://github.com/apache/hadoop.git -r 4ea602c1ee7b5e1a5560c6cbd096de4b140f776b
Compiled by ajay.kumar on 2019-04-30T03:25Z
Compiled with protoc 2.5.0
From source with checksum 45e58ba9203a1b4470e183bf90281b20

Using HDDS 0.4.0-alpha
Source code repository https://github.com/apache/hadoop.git -r 4ea602c1ee7b5e1a5560c6cbd096de4b140f776b
Compiled by ajay.kumar on 2019-04-30T03:24Z
Compiled with protoc 2.5.0
From source with checksum 57412e0def0317aed91721fb7ef5
```

How to test:

1. Single image version

```
./build.sh

docker run -p 9878:9878 -p 9876:9876  apache/ozone:latest

ls > /tmp/testfile
aws s3api --endpoint http://localhost:9878/ create-bucket --bucket=bucket1
aws s3 --endpoint http://localhost:9878 cp --storage-class REDUCED_REDUNDANCY /tmp/testfile  s3://bucket1/testfile
```

Yes, it's an ozone cluster in one line.

2. pseudo-cluster version

```
./build.sh
docker tag apache/ozone:latest  apache/ozone:0.4.0

mkdir /tmp/ozonetest
cd /tmp/ozonetest
#The required config files are inlined!!!
docker run apache/ozone:latest cat docker-config > docker-config
docker run apache/ozone:latest cat docker-config.yaml > docker-config.yaml

docker-compose up -d
docker-compose scale datanode=3

ls > /tmp/testfile
aws s3api --endpoint http://localhost:9878/ create-bucket --bucket=bucket1
aws s3 --endpoint http://localhost:9878 cp /tmp/testfile  s3://bucket1/testfile
```

### CODE REVIEW

**Comment by elek** [comment]
Note: the HDDS-1425 quick fix is also included (to be compatible with the latest docker-compose)

**Comment by ajayydv** [comment]
> 1. pseudo-cluster version
> 
> ```
> ./build.sh
> docker tag apache/ozone:latest  apache/ozone:0.4.0
> 
> mkdir /tmp/ozonetest
> cd /tmp/ozonetest
> #The required config files are inlined!!!
> docker run apache/ozone:latest cat docker-config > docker-config
> docker run apache/ozone:latest cat docker-config.yaml > docker-config.yaml
> 
> docker-compose up -d
> docker-compose scale datanode=3
> 
> ls > /tmp/testfile
> aws s3api --endpoint http://localhost:9878/ create-bucket --bucket=bucket1
> aws s3 --endpoint http://localhost:9878 cp /tmp/testfile  s3://bucket1/testfile
> ```

@elek  thanks for the PR. LGTM, However it seems steps mentioned for pseudo cluster needs correction. It is missing docker-compose.yaml.

**Comment by elek** [comment]
Thanks, you are right, the initialization should be:

```
docker run apache/ozone:latest cat docker-config > docker-config
docker run apache/ozone:latest cat docker-compose.yaml > docker-compose.yaml
```

**Review by arp7 — APPROVED** [review]
+1

**Comment by elek** [comment]
Thanks @arp7 and @ajayydv the review. I am merging it to the ozone-latest (and ozone-0.4.0) branches in the hadoop-docker-ozone repository.

**Pull request merged**
