### PR TITLE
HDDS-4203. Publish apache/ozone:1.0.0 image

### PR DESCRIPTION
**Pull request by elek**
Publish official docker image for ozone 1.0.0

## How is it tested

```
./build.sh
```

```
docker run -p 9876:9876 apache/ozone:1.0.0
# checked the 9876 and number of datanodes
```

```
docker run apache/ozone:1.0.0 cat docker-config > docker-config
docker run apache/ozone:1.0.0 cat docker-compose.yaml > docker-compose.yaml
docker-compose up -d
# checked the 9876 and number of datanodes
```

### CODE REVIEW

**Review by adoroszlai — APPROVED** [review]
Thanks @elek for working on this.  I have also built the image locally and checked it with Ozone's `upgrade` test.

**Comment by anusha-anuozone** [comment]
Can we try this with docker swarm

**Comment by elek** [comment]
Merged. Thanks the review @adoroszlai

**Comment by elek** [comment]
Merged. Thanks the review @adoroszlai

**Pull request merged**
