### PR TITLE
HDDS-5199. Create docker image for Apache Ozone 1.1.0 release

### PR DESCRIPTION
**Pull request by elek**
JIRA: https://issues.apache.org/jira/browse/HDDS-5199

After the release of Apache Ozone 1.1.0 we can publish the released/voted artifact in a different packaging: as a container image.

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @elek for working on this.  I think it would be better to start from `ozone-1.0.0`.  `latest` is very outdated (same as `0.3.0`), there were a number of fixes/improvements since then.

```
* e85e3c1 (HEAD -> ozone-1.1.0) Create docker image for Apache Ozone 1.1.0 release
| * 67d955b (origin/ozone-latest, origin/ozone-1.0.0) HDDS-4203. Publish apache/ozone:1.0.0 image (#16)
| * 0a69040 (origin/ozone-0.5.0, ozone-0.5.0) HDDS-3688. Create docker image for 0.5.0 release (#14)
| * f067f3e (origin/ozone-0.4.1) Fix Ozone Manager name mismatch in docker-compose.yaml and docker-config
| * 149f27e HDDS-2025. Update the base image of the apache/ozone and use latest 0.4.1 release. (#7)
| * ba3eaab (origin/ozone-0.4.0) HDDS-1526. Publish latest ozone release on dockerhub.
| ...
|/
* 8c847c8 (origin/latest, origin/0.3.0) HDDS-851. Provide official apache docker image for Ozone. Contributed by Elek, Marton.
```

**Comment by elek** [comment]
Thanks the review @adoroszlai. Will do it. But just found that we have #18 here. Maybe we can start it from there...

**Comment by elek** [comment]
@adoroszlai: I updated the latest based on #18, and rebased this patch.

Now all the changes are included and this PR became very simple :man_dancing:

**Review by adoroszlai — COMMENTED** [review]
Thanks @elek for updating the patch.

There are two places with `1.0.0` version leftover:

 * https://github.com/elek/ozone-docker/blob/c022c7e02bc415e17c7cee3c0e10ad76db79dc8f/docker-compose.yaml#L46
 * https://github.com/elek/ozone-docker/blob/c022c7e02bc415e17c7cee3c0e10ad76db79dc8f/build.sh#L34

Also, I think it would be nice to add this to `docker-config`:

```
OZONE_CONF_DIR=/etc/hadoop
OZONE_LOG_DIR=/var/log/hadoop
```

to prevent:

```
WARNING: HADOOP_CONF_DIR has been deprecated by OZONE_CONF_DIR.
WARNING: HADOOP_LOG_DIR has been deprecated by OZONE_LOG_DIR.
```

**Comment by elek** [comment]
> Also, I think it would be nice to add this to docker-config:

Good idea, but let me add it to the `Dockerfile` temporarily. there is a use-case where single container ozone is started with `docker run -d apache/ozone:1.1.0`  

Other problems should be with the last commits...

Also create apache/ozone-docker-runner#7 to fix it long-term...

**Review by adoroszlai — APPROVED** [review]
Thanks @elek for updating the patch.

**Comment by elek** [comment]
Thanks for the review @adoroszlai. Merging it now.

**Pull request merged**
