### PR TITLE
HDDS-11329. Update Ozone images to Rocky Linux-based runner

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Change `apache/ozone:1.4.0` to use the latest `apache/ozone-runner:20240729-jdk17-1` as base image.  It has Rocky Linux instead of CentOS (EOL) and comes with updated third-party software.

(Similar PRs for other Ozone versions will follow.)

## How was this patch tested?

- Built image locally.
- Started Docker Compose cluster and ran Freon.
- Ran Ozone's xcompat acceptance test.

### CODE REVIEW

**Review by smengcl — APPROVED** [review]
Thanks @adoroszlai .

Do we need this change for `latest` branch as well?:

https://github.com/apache/ozone-docker/blob/latest/Dockerfile#L16

**Comment by adoroszlai** [comment]
Thanks @smengcl for the review.  I have pushed this to branch [`ozone-1.4.0-rocky`](https://github.com/apache/ozone-docker/commits/ozone-1.4.0-rocky), and similar changes for other versions, to trigger automated image builds.  The new images are published with tags `1.4.0-rocky`, ..., `1.0.0-rocky` (see https://hub.docker.com/r/apache/ozone/tags)

Tested the new images with Ozone CI:
https://github.com/adoroszlai/ozone/actions/runs/10923350102

However, only `xcompat` and `upgrade` acceptance tests exercise these images.  Other tests use `ozone-runner` with the current Ozone code.

Old Ozone smoketests may not be fully compatible with the new OS (e.g. usage of `yum install` in S3 tests in some old Ozone versions).  We cannot fix that without overwriting parts of existing Ozone release in the Docker image -- I think we should avoid that.

I wonder which way we should proceed:

(1) keep the old images with existing content, and start using the new images with new tags, OR
(2) overwrite old images with new content?

**Comment by adoroszlai** [comment]
> Do we need this change for `latest` branch as well?:

Yes, `latest` should be patched (will do).

**Comment by adoroszlai** [comment]
> (1) keep the old images with existing content, and start using the new images with new tags,

@smengcl I've created https://github.com/apache/ozone/pull/7241 to switch Ozone to Rocky Linux using new tags

**Comment by adoroszlai** [comment]
Thanks @smengcl for the review.

Pushed this to `ozone-1.4.0-rocky`, keep `ozone-1.4.0` unchanged.

> > Do we need this change for `latest` branch as well?:
> 
> Yes, `latest` should be patched (will do).

Changed this PR to target `latest`.

**Comment by smengcl** [comment]
> I wonder which way we should proceed:
> 
> (1) keep the old images with existing content, and start using the new images with new tags, OR (2) overwrite old images with new content?

@adoroszlai Sorry I didn't notice this question earlier. I think it is generally preferrable to take approach (1).

I see you already took the first approach by appending `-rocky` to the image tag. :D

**Review by smengcl — APPROVED** [review]

**Pull request merged**
